###########
# Box Pool
###########

INSUFFICIENT_TOKENS_PROVIDED = "INSUFFICIENT_TOKENS_PROVIDED"
INSUFFICIENT_LOAN_AMOUNT = "INSUFFICIENT_LOAN_AMOUNT"
INVALID_RECEIVER_CONTRACT = "INVALID_RECEIVER_CONTRACT"

################
# Box Fruit NFT
################

TOKEN_ALREADY_PRESENT = "TOKEN_ALREADY_PRESENT"

###########
# Box Farm
###########
INVALID_BOX_ID = "INVALID_BOX_ID"
NOT_BOX_OWNER = "NOT_BOX_OWNER"
CANNOT_HARVEST_YET = "CANNOT_HARVEST_YET"
MERGE_PATTERN_ALREADY_PRESENT = "MERGE_PATTERN_ALREADY_PRESENT"

##########
# Generic
##########

NOT_AUTHORISED = "NOT_AUTHORISED"
INVALID_STATE = "INVALID_STATE"
